services:
  - type: web
    name: nextleap-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python Phase1_DataIngestion/data_loader.py && uvicorn Phase2_BackendAPI.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GROQ_API_KEY
        sync: false
